// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using System.CodeDom.Compiler;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    [GeneratedCode("Mutagen.Bethesda.FormKeys.Generator", "2.0.0")]
    public static partial class RaceCompatibility
    {
        public static class FormList
        {
            private static FormLink<IFormListGetter> Construct(uint id) => new FormLink<IFormListGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IFormListGetter> PlayableRaceList => Construct(0xd62);
            public static FormLink<IFormListGetter> PlayableVampireList => Construct(0xd63);
        }
    }
}
